spring.application.name=Catalogo_dbz
spring.datasource.url=jdbc:mysql://localhost:3306/figurasdbz
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true